### ISSUE TITLE
Passing context to data module?

### ISSUE THREAD

**Issue by droidwithme** [Drjacky/MVVM#4]
Hello DrJacky, 
Thanks for the amazing tutorial on clean architecture.
I am using this repo so far. but recently I wanted to check internet connectivity to check if user is offline, it yes then fetch data from database else from api.
To do that I need context in my repositoyimpl, How to do that?

**Comment by Drjacky** [comment]
@droidwithme The best practice could be that you do the network request, get the `UnknownHostException` or `SocketTimeoutException`, then on the Presentation layer, you act based on that.

This repo is old. I'd suggest taking a look into https://github.com/Drjacky/MVVMTemplate
